# Generated by Django 5.2.5 on 2025-08-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sharedlink',
            index=models.Index(fields=['file', 'expires_at'], name='files_share_file_id_bb861c_idx'),
        ),
    ]
