# Generated by Django 5.2.6 on 2025-09-12 15:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_sharedlink_files_share_file_id_bb861c_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='uploadedfile',
            constraint=models.UniqueConstraint(fields=('user', 'filename'), name='unique_filename_per_user'),
        ),
    ]
