# Generated by Django 5.2.6 on 2026-01-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0003_uploadedfile_unique_filename_per_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="expires_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
